### ISSUE TITLE
Authentication keeps login in/out

### ISSUE THREAD

**Issue by amolotkov** [mxtommy/Kip#321] opened 2024-03-11 15:57 UTC
When Autentication to Signal K enabled, the KIP continues to login/out
Here is the log from signal K
Mar 09 02:59:38 POST /signalk/v1/auth/login 200 149.473 ms - 163
Mar 09 02:59:38 PUT /signalk/v1/auth/logout 200 3.067 ms - 11
Mar 09 02:59:38 POST /signalk/v1/auth/login 200 128.401 ms - 163
Mar 09 02:59:39 PUT /signalk/v1/auth/logout 200 21.226 ms - 11
Mar 09 02:59:39 POST /signalk/v1/auth/login 200 153.815 ms - 163
Mar 09 02:59:39 PUT /signalk/v1/auth/logout 200 3.115 ms - 11
Mar 09 02:59:39 POST /signalk/v1/auth/login 200 117.094 ms - 163
Mar 09 02:59:39 PUT /signalk/v1/auth/logout 200 2.121 ms - 11
Mar 09 02:59:39 POST /signalk/v1/auth/login 200 120.215 ms - 163
Mar 09 02:59:39 PUT /signalk/v1/auth/logout 200 2.292 ms - 11
Mar 09 02:59:39 POST /signalk/v1/auth/login 200 121.839 ms - 163
Mar 09 02:59:39 PUT /signalk/v1/auth/logout 200 2.366 ms - 11
Mar 09 02:59:39 POST /signalk/v1/auth/login 200 120.005 ms - 163
Mar 09 02:59:40 PUT /signalk/v1/auth/logout 200 2.915 ms - 11
Mar 09 02:59:40 POST /signalk/v1/auth/login 200 119.805 ms - 163
Mar 09 02:59:40 PUT /signalk/v1/auth/logout 200 2.094 ms - 11
Mar 09 02:59:40 POST /signalk/v1/auth/login 200 133.732 ms - 163
Mar 09 02:59:40 PUT /signalk/v1/auth/logout 200 1.870 ms - 11
Mar 09 02:59:40 POST /signalk/v1/auth/login 200 127.404 ms - 163

**Comment by godind** [comment] 2024-03-11 22:18
This is a duplicate of #318

It is cause by the NEVER value in the Signal K / Security / Remember ME Timeout parameter. Change to "1d" or another value for a temporary fix.

An update is comme soon to KIP.

Thank you

**Comment by amolotkov** [comment] 2024-03-12 03:17
Thank you

**Closed** 2024-03-17 12:19 UTC
