### ISSUE TITLE
Historic DataSet widget - initial value incorrect and persisted forever

### ISSUE THREAD

**Issue by tvr256** [mxtommy/Kip#171] opened 2023-03-06 18:45 UTC
I'm trying to use the Historical DataSet widget to display changes in barometric pressure. I'm capturing pressure every 5 minutes for the last 8 hours:

![image](https://user-images.githubusercontent.com/117984987/223200818-1dc42ca8-0e4e-4df6-a779-da052470b59d.png)

There are 2 separate issues. Firstly the initial value is extremely low, which throws out the scale and makes it hard to see small changes. Secondly the initial values don't disappear after 8 hours, instead they seem to stay forever:

![image](https://user-images.githubusercontent.com/117984987/223201981-7c9c15b0-0ebb-4f36-9fb1-40c40aebc25c.png)

**Comment by JonyIvy** [comment] 2023-03-07 09:43
For this use case I'm embedding a Grafana dashboard, which shows a graph of the pressure (data comes from InfluxDB). This way you have better access to the data and can configure the graph just the way you like.

**Comment by godind** [comment] 2023-11-21 05:43
Maybe be caused by sensor null values. We will if a filter fixes the issue.

**Comment by godind** [comment] 2023-11-26 08:04
This should be fixed (null or undefined value in datasets) in the next release.

Thank you

**Closed** 2023-11-26 08:04 UTC
Labels: bug
