### ISSUE TITLE
Radial gauge spinning

### ISSUE THREAD

**Issue by JonyIvy** [mxtommy/Kip#222] opened 2023-11-22 17:49 UTC
Sometimes my radial gauge which displays SOG starts spinning, the whole gauge, not the finger. After reload it's fine again.

This only happened on Safari so far (both iPad and Mac).

<img width="353" alt="Bildschirmfoto 2023-11-22 um 18 48 35" src="https://github.com/mxtommy/Kip/assets/6115974/7c86eaec-112d-419e-b677-d2e1cf6a7f5a">

**Comment by JonyIvy** [comment] 2023-11-22 19:49
![Safari Console](https://github.com/mxtommy/Kip/assets/6115974/bd53e1d0-b1e7-4413-998f-76a6db276488)

**Comment by godind** [comment] 2023-11-23 00:33
Hum... that's probably a problem in one of the gauge framework KIP uses. I'll take a look but we might have to wait for an update from the publisher. Which in open source is not always very frequent.

Can you share browser and OS version info and test the with another browser to see if it has the same issue. I noticed Firefox seems to have more issues with this gauge library. 

Use a steelgauge widget instead. It offers the same functionality. That should fix the problem but it does not look the same.

**Comment by JonyIvy** [comment] 2023-11-23 09:31
Safari Version 17.1 (18616.2.9.11.9, 18616) on Mac
Safari on iPadOS 16.7 (20H19)

I could not reproduce this behaviour on Firefox or Chrome.

**Comment by godind** [comment] 2023-11-23 21:02
I've been running on MacOs Safari 16.5 for 12h with no issue. I'll upgrade to the latest and see if it shows up. I'm beginning to suspect that fidget maybe gets bad data that messes things up.

**Comment by godind** [comment] 2023-11-23 21:10
Are you using a stream file or it's live on your boat?

**Comment by JonyIvy** [comment] 2023-11-24 10:46
I'm using a stream file. It happens at seemingly random times in the stream. The only pattern I see is that the bug appears about every 12 minutes on iPad, 14 minutes on Mac. I tested this for more than an hour.

**Comment by godind** [comment] 2023-12-05 00:07
I can't reproduce and no other user has reported this, yet... so I think it might be related to data values. The latest 2.3 release has better filtering of null values.

Try and see if it fixes the problem.

**Comment by godind** [comment] 2023-12-21 04:42
Have you seen the problem in the latest release?

**Comment by JonyIvy** [comment] 2023-12-21 09:06
Nope, it has been working fine since one hour now. :)

**Comment by JonyIvy** [comment] 2023-12-21 13:58
Yes it is still happening. I will test with SK simulator data now to make sure it's not my logged data.

**Comment by godind** [comment] 2024-01-14 23:44
There is a fix on the Canvas-Gauge package to fix this. It's been pending 3 years in PR... I sent an email to the owner. Maybe we'll need to switch gauge library... Thant would be a lot of work :(

**Comment by godind** [comment] 2024-02-27 06:02
still have this issue? I've never been able to reproduce so far. Not sure what the problem is and no one reported a similar problem.

**Comment by JonyIvy** [comment] 2024-03-03 22:22
I have seen it today with the latest version of KIP but still with my old data log.

**Comment by godind** [comment] 2024-03-04 17:09
It's probably related to the computer it's running on. Check for OS, browser and node updates.

**Comment by godind** [comment] 2024-05-28 00:50
This should be fixed in V2.10. Please have a look and report back. Thank you for your patience!

**Closed by godind** 2024-05-28 00:50 UTC
Labels: bug, widget
