### ISSUE TITLE
Canvas gauge change position in Firefox

### ISSUE THREAD

**Issue by mxtommy** [mxtommy/Kip#84] opened 2021-07-11 22:38 UTC
Kip affected by this: https://github.com/Mikhus/canvas-gauges/issues/232

**Comment by godind** [comment] 2022-11-16 23:47
Can't reproduce the issue with v107.0x. Resolved?

**Comment by philipa** [comment] 2023-04-10 11:18
I'm here because I've just seen this with 1.3.0, so not resolved.

**Comment by godind** [comment] 2023-10-09 02:45
Not sure what can be done. It's a dependency issue (a gauge toolkit). Can't you another browser? Firefox is about 2.5% of the market and I doubt the library owner will fix it.

Closing issue...

**Closed by godind** 2023-10-09 02:45 UTC
Labels: bug

**Comment by CttCJim** [comment] 2026-06-08 15:32
I solved it. https://github.com/Mikhus/canvas-gauges/issues/232#issuecomment-4650363083
